AllCops:
  TargetRubyVersion: 2.3

# Trailing commas in a multiline context makes diffs nicer.
Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: comma

# Trailing commas in a multiline context makes diffs nicer.
Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma

# Trailing commas in a multiline context makes diffs nicer.
Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: comma

# This allows for semantic exceptions
Style/RaiseArgs:
  Enabled: false

# We should embrace UTF-8, not shun it.
Style/AsciiComments:
  Enabled: false

# This does not always make sense (e.g. for tests cases)
Style/Documentation:
  Enabled: false

# Explicitly returning nil in an else is sometimes more clear.
Style/EmptyElse:
  Enabled: false

# If/unless at the end of the line makes it harder to miss control flow.
Style/IfUnlessModifier:
  Enabled: false

# This doesn’t always make sense.
Style/GuardClause:
  Enabled: false

# For testing.
Style/GlobalVars:
  AllowedVariables:
    - "$did_it_work"

# Not accurate in tests
Lint/NestedMethodDefinition:
  Exclude:
    - 'test/**/*.rb'

Naming/HeredocDelimiterNaming:
  Enabled: false

# Will re-enable later.

Metrics/AbcSize:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/LineLength:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Style/FormatStringToken:
  Enabled: false

Style/EvalWithLocation:
    Exclude:
    - 'test/**/*.rb'
