# This makes DSLs a little uglier, since it makes sense to line up the first
# arguments:
#
#   option    :a, :aaa, 'opt a', :argument => :optional, :multiple => true
#   required  :b, :bbb, 'opt b'
#   optional  :c, :ccc, 'opt c'
#   flag      :d, :ddd, 'opt d'
Style/SingleSpaceBeforeFirstArg:
  Enabled: false

# We require Ruby 1.8.6+ compatibility, so hash rockets is the enforced style.
Style/HashSyntax:
  EnforcedStyle: hash_rockets




# Offense count: 1
Lint/AmbiguousRegexpLiteral:
  Enabled: false

# Offense count: 1
Lint/ShadowingOuterLocalVariable:
  Enabled: false

# Offense count: 23
# Cop supports --auto-correct.
# Lint/UnusedBlockArgument:
#   Enabled: false

# Offense count: 3
# Cop supports --auto-correct.
# Lint/UnusedMethodArgument:
#   Enabled: false

# Offense count: 16
Lint/UselessAssignment:
  Enabled: false

# Offense count: 1
Lint/Void:
  Enabled: false

# Offense count: 25
Metrics/AbcSize:
  Max: 45

# Offense count: 6
# Configuration parameters: CountComments.
Metrics/ClassLength:
  Max: 423

# Offense count: 2
Metrics/CyclomaticComplexity:
  Max: 8

# Offense count: 38
# Configuration parameters: AllowURI, URISchemes.
Metrics/LineLength:
  Max: 139

# Offense count: 33
# Configuration parameters: CountComments.
Metrics/MethodLength:
  Max: 41

# Offense count: 1
Metrics/PerceivedComplexity:
  Max: 9

# Offense count: 3
# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, SupportedStyles.
# Style/AccessModifierIndentation:
#   Enabled: false

# Offense count: 5
# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, SupportedStyles.
# Style/AlignParameters:
#   Enabled: false

# Offense count: 3
# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, SupportedStyles.
# Style/AndOr:
#   Enabled: false

# Offense count: 11
Style/AsciiComments:
  Enabled: false

# Offense count: 2
# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, SupportedStyles.
Style/BracesAroundHashParameters:
  Enabled: false

# Offense count: 12
# Configuration parameters: EnforcedStyle, SupportedStyles.
Style/ClassAndModuleChildren:
  Enabled: false

# Offense count: 1
# Configuration parameters: Keywords.
Style/CommentAnnotation:
  Enabled: false

# Offense count: 15
Style/Documentation:
  Enabled: false

# Offense count: 1
Style/DoubleNegation:
  Enabled: false

# Offense count: 2
Style/EmptyElse:
  Enabled: false

# Offense count: 35
# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, SupportedStyles.
# Style/EmptyLinesAroundClassBody:
#   Enabled: false

# Offense count: 1
# Cop supports --auto-correct.
# Style/EmptyLinesAroundMethodBody:
#   Enabled: false

# Offense count: 25
# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, SupportedStyles.
# Style/EmptyLinesAroundModuleBody:
#   Enabled: false

# Offense count: 1
# Configuration parameters: EnforcedStyle, SupportedStyles.
Style/FormatString:
  Enabled: false

# Offense count: 8
# Configuration parameters: AllowedVariables.
Style/GlobalVars:
  Enabled: false

# Offense count: 3
# Configuration parameters: MinBodyLength.
Style/GuardClause:
  Enabled: false

# Offense count: 2
# Configuration parameters: MaxLineLength.
Style/IfUnlessModifier:
  Enabled: false

# Offense count: 1
# Cop supports --auto-correct.
Style/IndentArray:
  Enabled: false

# Offense count: 31
# Cop supports --auto-correct.
# Style/LineEndConcatenation:
#   Enabled: false

# Offense count: 2
# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, SupportedStyles.
# Style/MultilineOperationIndentation:
#   Enabled: false

# Offense count: 1
# Cop supports --auto-correct.
# Style/NegatedIf:
#   Enabled: false

# Offense count: 2
# Cop supports --auto-correct.
# Style/PerlBackrefs:
#   Enabled: false

# Offense count: 4
# Configuration parameters: EnforcedStyle, SupportedStyles.
Style/RaiseArgs:
  Enabled: false

# Offense count: 1
# Cop supports --auto-correct.
# Style/RedundantBegin:
#   Enabled: false

# Offense count: 15
# Cop supports --auto-correct.
# Style/RedundantSelf:
#   Enabled: false

# Offense count: 9
# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, SupportedStyles.
# Style/SignalException:
#   Enabled: false

# Offense count: 7
# Cop supports --auto-correct.
# Configuration parameters: AllowIfMethodIsEmpty.
# Style/SingleLineMethods:
#   Enabled: false

# Offense count: 2
# Cop supports --auto-correct.
# Style/SpaceAfterComma:
#   Enabled: false

# Offense count: 13
# Cop supports --auto-correct.
# Configuration parameters: SupportedStyles.
Style/SpaceAroundEqualsInParameterDefault:
  EnforcedStyle: no_space

# Offense count: 1
# Cop supports --auto-correct.
# Style/SpaceAroundOperators:
#   Enabled: false

# Offense count: 14
# Cop supports --auto-correct.
# Style/SpaceBeforeSemicolon:
#   Enabled: false

# Offense count: 116
# Cop supports --auto-correct.
# Style/SpaceInsideBrackets:
#   Enabled: false

# Offense count: 1
# Cop supports --auto-correct.
# Style/SpaceInsideParens:
#   Enabled: false

# Offense count: 33
# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, SupportedStyles.
Style/StringLiterals:
  Enabled: false

# Offense count: 5
# Cop supports --auto-correct.
# Configuration parameters: IgnoredMethods.
Style/SymbolProc:
  Enabled: false

# Offense count: 3
# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyleForMultiline, SupportedStyles.
Style/TrailingComma:
  Enabled: false

# Offense count: 3
# Cop supports --auto-correct.
# Configuration parameters: ExactNameMatch, AllowPredicates, AllowDSLWriters, Whitelist.
Style/TrivialAccessors:
  Enabled: false

# Offense count: 10
# Cop supports --auto-correct.
# Configuration parameters: WordRegex.
Style/WordArray:
  MinSize: 3
