# This makes DSLs a little uglier, since it makes sense to line up the first
# arguments:
#
#   option    :a, :aaa, 'opt a', :argument => :optional, :multiple => true
#   required  :b, :bbb, 'opt b'
#   optional  :c, :ccc, 'opt c'
#   flag      :d, :ddd, 'opt d'
Style/SingleSpaceBeforeFirstArg:
  Enabled: false

# We require Ruby 1.8.6+ compatibility, so hash rockets is the enforced style.
Style/HashSyntax:
  EnforcedStyle: hash_rockets

# Trailing commas in a multiline context makes diffs nicer.
Style/TrailingComma:
  EnforcedStyleForMultiline: comma

# We require Ruby 1.8.6+ compatibility, so we can’t use symbol procs.
Style/SymbolProc:
  Enabled: false

# This doesn’t always make sense (e.g. Cri::ArgumentArray#raw)
Style/TrivialAccessors:
  Enabled: false

# This allows for semantic exceptions
Style/RaiseArgs:
  Enabled: false

# We should embrace UTF-8, not shun it.
Style/AsciiComments:
  Enabled: false

# This does not always make sense (e.g. for tests cases)
Style/Documentation:
  Enabled: false

# Will re-enable later.
Metrics/AbcSize:
  Max: 45
Metrics/ClassLength:
  Max: 436
Metrics/CyclomaticComplexity:
  Max: 8
Metrics/LineLength:
  Max: 141
Metrics/MethodLength:
  Max: 41
Metrics/PerceivedComplexity:
  Max: 9

# Offense count: 1
Style/DoubleNegation:
  Enabled: false

# Offense count: 2
Style/EmptyElse:
  Enabled: false

# Offense count: 1
# Configuration parameters: EnforcedStyle, SupportedStyles.
Style/FormatString:
  Enabled: false

# Offense count: 8
# Configuration parameters: AllowedVariables.
Style/GlobalVars:
  Enabled: false

# Offense count: 3
# Configuration parameters: MinBodyLength.
Style/GuardClause:
  Enabled: false

# Offense count: 2
# Configuration parameters: MaxLineLength.
Style/IfUnlessModifier:
  Enabled: false
