# This makes DSLs a little uglier, since it makes sense to line up the first
# arguments:
#
#   option    :a, :aaa, 'opt a', :argument => :optional, :multiple => true
#   required  :b, :bbb, 'opt b'
#   optional  :c, :ccc, 'opt c'
#   flag      :d, :ddd, 'opt d'
Style/SpaceBeforeFirstArg:
  Enabled: false

# Trailing commas in a multiline context makes diffs nicer.
Style/TrailingCommaInLiteral:
  EnforcedStyleForMultiline: comma

# Trailing commas in a multiline context makes diffs nicer.
Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: comma

# This doesn’t always make sense (e.g. Cri::ArgumentArray#raw)
Style/TrivialAccessors:
  Enabled: false

# This allows for semantic exceptions
Style/RaiseArgs:
  Enabled: false

# We should embrace UTF-8, not shun it.
Style/AsciiComments:
  Enabled: false

# This does not always make sense (e.g. for tests cases)
Style/Documentation:
  Enabled: false

# Explicitly returning nil in an else is sometimes more clear.
Style/EmptyElse:
  Enabled: false

# If/unless at the end of the line makes it harder to miss control flow.
Style/IfUnlessModifier:
  Enabled: false

# This doesn’t always make sense.
Style/GuardClause:
  Enabled: false

# For testing.
Style/GlobalVars:
  AllowedVariables:
    - "$did_it_work"

# Not accurate in tests
Lint/NestedMethodDefinition:
  Exclude:
    - 'test/**/*.rb'

# Will re-enable later.
Metrics/AbcSize:
  Max: 45
Metrics/ClassLength:
  Enabled: false
  Max: 436
Metrics/CyclomaticComplexity:
  Max: 8
Metrics/LineLength:
  Enabled: false
  Max: 141
Metrics/MethodLength:
  Max: 41
Metrics/PerceivedComplexity:
  Max: 9
